- .gitignore
- frontend/package.json
- frontend/src/App.vue
- frontend/src/layout/nav.vue
- frontend/src/main.js
- frontend/src/router.js
- frontend/src/serve-citizen/dash-buttons.vue
- frontend/src/serve-citizen/dash.vue
- frontend/src/smartboard/call-by-name.vue
- frontend/src/smartboard/call-by-ticket.vue
- frontend/src/smartboard/index.vue
- frontend/src/store/index.js
Added vue-router to project
-created route for The Q ('/queue') and auto-redirect from '/' to '/queue' so navigation unchanged
-created component 'Nav' to hold navigation and router-subviews (view-content and buttons slots)
-flagged navigation menu as hidden until needed in future
-extracted buttons from Dash component for rendering in the buttons router-view slot
-created route for smartboard ('/smartboard/')
-adapted the office_id computed property to receive URL params from vue-router ('/smartboard/:id')
> Added vue-router to project

- api/app/models/bookings/exam.py
- api/app/resources/bookings/booking/booking_delete.py
- api/app/resources/bookings/booking/booking_detail.py
- api/app/resources/bookings/booking/booking_list.py
- api/app/resources/bookings/booking/booking_post.py
- api/app/resources/bookings/booking/booking_put.py
Finalized models/schemas/resources for the Friday Postman acceptance test demo.
> Create database models, schemas, end-points

- api/app/resources/bookings/booking/booking_delete.py
Removed typo from the booking delete end-point to allow for the function to work properly.
> Booking DELETE typo fix

- api/app/resources/bookings/exam/exam_list.py
The bookings feature required search functionality such that parameters are passed via URL to the exams GET end-point. These parameters are then added to the query filter. Testing was completed using bootstrapped data and passing single or multiple different parameters to ensure that the returned values were as expected.
> Search for Existing Exams Functionality

- frontend/src/exams/add-exam-form-components.js
- frontend/src/exams/add-exam-form-confirm.vue
- frontend/src/exams/add-exam-form-controller.vue
- frontend/src/exams/add-exam-form-modal.vue
- frontend/src/exams/exam-inventory-table.vue
- frontend/src/store/index.js
created http post action and mutation and data validation methods to handle input from the add-ita-exam form and post to backend.
> Http post methods / validation of data for add-ita-exam form

- documentation/open-api/swagger.yaml
Updated the swagger spec after updating some data types, adding and removing fields from specific models and updating the nullable values for each field after HTTP method testing on the front end
> Updated Swagger Spec

- frontend/src/agenda/agenda.vue
- frontend/src/agenda/buttons-agenda.vue
- frontend/src/layout/nav.vue
- frontend/src/main.js
- frontend/src/router.js
- frontend/src/store/index.js
added route for room booking (/booking/) and created two basic full-calendar views (dayList and weekList) customized to render the resourceTitle with custom navigation external to the calendar component.
> View exam bookings

- api/manage.py
- api/migrations/versions/cf50e7b9a32c_.py
Backend was seeing multiple heads (branch conflict) when doing the upgrade->migrate->upgrade process. This needed to be addressed, and manage.py needed it's bootstrap data updated as well.
> Database Version Update

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.vue
- frontend/src/agenda/agenda.vue
- frontend/src/agenda/buttons-agenda.vue
- frontend/src/assets/css/q.css
- frontend/src/booking/calendar.vue
- frontend/src/booking/dropdown-calendar.vue
- frontend/src/booking/other-booking-modal.vue
- frontend/src/booking/scheduling-indicator.vue
- frontend/src/exams/add-exam-form-controller.vue
- frontend/src/exams/exam-inventory-table.vue
- frontend/src/layout/footer.vue
- frontend/src/layout/nav.vue
- frontend/src/store/index.js
Addressed the following issues:
Fixed increment/decrement buttons in OtherBookingModal
Fixed issue where verticalResourceView became active in month calendar view
Fixed issues with eventRender and viewRender functions In Office Agenda view
Fixed issue causing scroll bars to appear in error on Calendar views
Fixed issue where dayClick on month view created day-long event
Fixed issue with FullCalendar height on month views
Fixed issue where answering Yes to ‘Exam Received Today?’ In Ind ITA exam capture caused post failure
Fixed issue with invigilator not attaching to bookings
Also made the following improvements:
Added room colour legend to all FullCalendar views
Renamed Navigation items Office Agenda and Exam Admin
Created an improved SchedulingIndicator and placed in separate component
> Numerous bug fixes and functionality improvements following Jan-8 demo

- api/manage.py
- frontend/package-lock.json
- frontend/src/assets/css/q.css
- frontend/src/exams/edit-exam-form-modal.vue
- frontend/src/exams/exam-inventory-table.vue
- frontend/src/exams/return-exam-form-modal.vue
- frontend/src/store/index.js
CSRs require the ability to update existing exams records in the exam inventory table. This comes in the form of two actions listed as dropdown items in the exam inventory table now. The first action (Edit Exam) shows the user basic information that is displayed in the table, and allows the user to edit said data, then submit the data to the database. The second action (Return Exam) allows the user to enter or edit information with respect to the exam being returned (an ind field and tracking information). Both actions upon submit display a relevent success or failure message depending on the return method response.
> Make Updates to an Existing Exam Record

- frontend/package-lock.json
- frontend/package.json
- frontend/src/admin.vue
- frontend/src/agenda/agenda.vue
- frontend/src/booking/calendar.vue
- frontend/src/booking/edit-booking-modal.vue
- frontend/src/booking/other-booking-modal.vue
- frontend/src/exams/add-exam-form-components.js
- frontend/src/exams/add-exam-form-confirm.vue
- frontend/src/exams/add-exam-form-controller.vue
- frontend/src/exams/add-exam-form-modal.vue
- frontend/src/exams/buttons-exams.vue
- frontend/src/exams/exams.vue
- frontend/src/exams/inventory-filters.vue
- frontend/src/layout/nav.vue
- frontend/src/store/index.js
Created a new set of steps and questions in the state corresponding to the data requirements for the capture of Group ITA Exams to drive the add exam modal.  Created new question components and modified the modal to support the capture ofgroup exams as needed.
> Add Group Exam Modal/ITA Group Exam Capture

- frontend/src/App.vue
Socket connection was not being initialized due to the socket component being placed behind logic that precluded it from doing so in error.  Fixed
> Fixed issue where socket was no longer connecting

- frontend/src/add-citizen/add-citizen.vue
- frontend/src/assets/css/q.css
Created class in q.css with zero padding and applied to necessary modals via body-class prop as it should have been done.
> Fixed issue with modal padding

- api/app/resources/bookings/exam/exam_export_list.py
- api/manage.py
- api/migrations/sql_scripts/exam_types.sql
- frontend/src/exams/generate-financial-report-modal.vue
Further development on the generate CSV modal required exam type filtering to be completed. Based on the exam type elected via radio button, a url parameter is passed to the GET method used to generate the final csv. Based on the parameter provided, dynamic filtering is done to the exam object created via query.
> Generate Financial Report - Exam Type Filtering

- api/postman/bookings-postman.json
Previously in sprint-6, modifications were made to the exam model, which required modifications to be made to the postman tests. All modifications have been tetsted to ensure that all test cases pass 100%
.
> Exam Model Postman Updates

- frontend/src/App.vue
fixed the issue of navigation jitter when opening the hamburger menu affecting internet explorer
> Fixed issue with hamburger menu jitter in ie

- api/app/resources/bookings/exam/exam_export_list.py
During testing of the bookings feature, it was found that the generate csv function was unreliable due to how tables were joined. This was fixed by doing a left outer join on the invigilator table from the booking table. Also, during testing, it was found that the CSV was not showing values as required. The Exam Returned and Exam Received fields were showing 0's and 1's and not Y's and N's. Logic was added to the exam export endpoint to handle these requirements. Thorough testing was completed to ensure that CSV files were returning correct values for one and many exams in different month periods.
> Generate CSV Bugs

- frontend/src/exams/add-exam-form-components.js
Added a simple alphabetical sorter to the array of exam_types
> Fixed bug: inconsistent sorting of exam_types in AddExamModal

- frontend/src/exams/exam-inventory-table.vue
Added pagination to exam inventory table to limit the table to display of 10 items at a time.
> Fixed Bug: Inconsistent page breaking r/i Loss of Scroll

- frontend/src/exams/add-exam-form-controller.vue
- frontend/src/exams/add-exam-modal.vue
- frontend/src/exams/exam-inventory-table.vue
- frontend/src/exams/office-drop.vue
- frontend/src/store/index.js
Added an additional filter button to the top of the ExamInventory for filtering offices that is only visible to LIAISONs.  Clicking on it brings up an office search so they can select another office to display in the table.
> Added ability for LIAISONs to filter offices in ExamInventory

- frontend/src/exams/add-exam-form-confirm.vue
- frontend/src/exams/exam-inventory-table.vue
Also, changed the actions column to only display options 'edit exam' and 'delete exam' when LIAISON is viewing inventory out of their own office.  Also, fixed a bug in the summary/confirmation view of the Add Exam Modal where there was a missing < in the html markup causing display issues.
> Added exam_type to the exam inventory table

- frontend/src/appointments/appointments.vue
- frontend/src/appointments/buttons-appointments.vue
- frontend/src/layout/nav.vue
- frontend/src/router.js
As required by clients, the bookings feature needs a separate page for an appointments calendar. To begin development on this, a component for the page and its buttons needed to be created, and additions to the application router and nav bar needed to be made in order to navigate to this new page. Future development for this page will include implementing a calendar component on the page that has similar functionality to the exams calendar, but implements black out periods.
> Appointments - Page and Navigation

- frontend/src/assets/css/q.css
- frontend/src/booking/booking-modal.vue
- frontend/src/booking/calendar.vue
- frontend/src/booking/edit-booking-modal.vue
- frontend/src/booking/scheduling-indicator.vue
- frontend/src/exams/add-exam-form-components.js
- frontend/src/exams/add-exam-form-confirm.vue
- frontend/src/exams/add-exam-form-controller.vue
- frontend/src/exams/add-exam-modal.vue
- frontend/src/exams/buttons-exams.vue
- frontend/src/exams/edit-exam-form-modal.vue
- frontend/src/exams/exam-inventory-table.vue
- frontend/src/store/add-exam-module.js
- frontend/src/store/index.js
Created an appropriate questions object for Challenger Exams.  Created a store module for the addExamModal and relocated some of the addExamModals data and logic into this module.  Modified the BookingModal, the SchedulingIndicator and the AddExamModal to support onsite or offsite booking of thechallenger exams.  Also modified the ExamInventoryTable to support the Challenger Exams.
> Added Ability to Schedule Challenger Exam

- frontend/src/booking/calendar.vue
- frontend/src/exams/exam-inventory-table.vue
- frontend/src/store/index.js
Changed the way the calendar renders resources to the intended way of asynchronously loading roomResources via resource loader function in config.  Made provisions to automatically show or hide the offsite room depending on user preference (in the store) and persist this preference after naviagion.  added toggle switch.  also fixed some typos in ExamInventoryTable.
> Added Offsite visibility toggle to calendar and corrected typo

- frontend/src/serve-citizen/dash.vue
Navigation guard on dash.vue was blocking navigation away.  Fixed issue.`
> Fixed issue where navigation to Admin Panel was not possible.

- api/app/resources/theq/csrs.py
- frontend/src/App.vue
- frontend/src/exam-alert.vue
- frontend/src/login-warning.vue
- frontend/src/store/index.js
During client testing, it was found that exam notifications weren't working cons
istently. Minor typos were found in store functions and in the exam alert compon
ent itself that were hindering functionality of the notifications. Testing inclu
ded making both individual and group exams to trigger notifications given criter
ia, and making sure the appropriate messages were being shown. Testing also cros
sed office boundaries to make sure that notifications were specific to the user
based on what office they belong to.
> Exam Notifications

- documentation/open-api/swagger.yaml
Client requires updated data structure for new models/schemas as well as updates to current models/schemas.
> Swagger Update

- api/app/admin/csr.py
- api/app/resources/theq/offices.py
- api/app/utilities/snowplow.py
- api/manage.py
- frontend/src/admin.vue
- frontend/src/exams/edit-group-exam-modal.vue
- frontend/src/exams/exam-inventory-table.vue
- frontend/src/layout/footer.vue
- frontend/src/store/index.js
Multiple commits fixing sonarqube minor smells per file.
> SonarQube Minor Code Smell Resolutions

- api/app/resources/theq/login.py
- api/app/resources/theq/websocket.py
- frontend/src/exams/add-exam-form-controller.vue
Multiple commits fixing sonarqube major smells per file.
> SonarQube Major Code Smells Resolutions

- api/config.py
Make this IP address configurable (local variable)
> SonarQube Vulnerability Resolution

- api/app/resources/bookings/exam/exam_export_list.py
During client testing, it was found that there were missing columns required when generating a csv for financial reporting purposes. The sbc_staff_invigilated, start_time, end_time, number_of_students and notes fields were added to the generated csv file.
This PR also attempts to reduce the complexity of the exam_export_list.py to meet sonarqube specifications by reducing complex/nested if/else statements and increasing modularity by creating smaller working functions.
> Generate CSV - GA Reporting

- api/manage.py
- api/migrations/sql_scripts/exam_types.sql
Client found issues with the manage script after rebuilding the database on the test server.
> SQL Script Clean-up

- frontend/src/add-citizen/add-citizen.vue
- frontend/src/add-citizen/form-components/buttons.vue
- frontend/src/add-citizen/form-components/channel.vue
- frontend/src/add-citizen/form-components/filters.vue
- frontend/src/add-citizen/form-components/tables.vue
- frontend/src/appointments/appointments.vue
- frontend/src/appointments/appt-booking-modal/appt-booking-modal.vue
- frontend/src/appointments/buttons-appointments.vue
- frontend/src/appointments/checkin-modal.vue
- frontend/src/booking/booking-modal.vue
- frontend/src/booking/edit-booking-modal.vue
- frontend/src/booking/other-booking-modal.vue
- frontend/src/buttons-admin.vue
- frontend/src/exams/edit-group-exam-modal.vue
- frontend/src/exams/exam-inventory-table.vue
- frontend/src/exams/return-exam-form-modal.vue
- frontend/src/store/appointments-module.js
- frontend/src/store/index.js
Added another full-calendar based component to the application for handling appointments for services provided at serviceBC offices through the existing Q application.  Citizens are booked by name into 15 minute slots on the branch Appointent Calendar and when they arive, they can be checked directly into the Q.
> Q-Service Appointments Booking

- frontend/package-lock.json
- frontend/src/exams/add-exam-modal.vue
- frontend/src/exams/edit-group-exam-modal.vue
- frontend/src/exams/exam-inventory-table.vue
- frontend/src/exams/return-exam-form-modal.vue
- frontend/src/store/add-exam-module.js
- frontend/src/store/index.js
Added onsite/offsite question to the add Other Exam form workflow with default value set to onsite.  Selecting offsite causes the exam to be posted with offsite_location = '_offsite' which then causes the exam to be booked in the Edit Group Booking Modal when choosing the Scheduling Action later from the exam inventory table.
Adjusted the logic in the exam inventory table to facilitate this new option.
> Added Ability to Schedule "Other" exams to offsite locations

- api/postman/bookings-env-postman.json
- api/postman/bookings-postman.json
Postman tests for the bookings application now supports dynamic environment variables, such that the user that runs the test no longer has to re-build their backend each time they run the test suite.
> Dynamic Postman Environment Variables

- frontend/babel.config.js
- frontend/package-lock.json
- frontend/package.json
Inadvertently a non-functioning, test version of the babel config file was committed with the last PR.  Commiting the real version with this.
> Added proper, working babel.config.js to project

- frontend/src/booking/booking-modal.vue
- frontend/src/booking/calendar.vue
- frontend/src/exams/data-summary-table.vue
- frontend/src/store/index.js
Due to issues with IE 11 and the document.activeElement call, Bootstrap Modals were not working in this situation so re-wrote the component as a div box styled to match bootstrap with the necessary logic to replace the modal hooks.  also fixed issues with selection of invigilators and added logic to auto focus on the text input when opening.
> Re-built the Booking Modal as plain CSS div container

- frontend/src/booking/buttons-calendar.vue
- frontend/src/booking/dropdown-calendar.vue
- frontend/src/exams/add-exam-modal.vue
- frontend/src/test/bookings-book-exam.test.js
This PR contains the jest test responsible for booking an exam. It first creates an individual exam, then books the exam on the day after the current date. This test is meant to be run with an empty booking table, and can be run with exams in the exam inventory table. To run this test type `npm test -t bookings-book-exam` in command line.
> Jest Tests - Booking an Exam

- frontend/src/exams/edit-exam-form-modal.vue
- frontend/src/exams/edit-group-exam-modal.vue
and fixed minor issue with EditGroupBookingModal that may have been causing reactivity issues.
> eFixed Issue with ExamType Selection Field on EditExamFormModal

- frontend/src/exams/edit-group-exam-modal.vue
- frontend/src/exams/exam-inventory-table.vue
Form now requires Date, Time and Offsite Location when booking an Other Exam offsite initially and subsequently when editing an exam will allow submit with any single field having changed.  Supports booking SBC Staff invigilators now as well.
> Fixed Issues with Previous PR fixing EditGroupBookingModal

- frontend/src/exams/edit-group-exam-modal.vue
- frontend/src/exams/exam-inventory-table.vue
- frontend/src/exams/office-drop.vue
- frontend/src/test/bookings-session-exam.test.js
Fixed issues with moment.js and and moment-timezone in setValue and submit methods.
> Fixed Edit Group Booking Modal Update Date/Time for Group/Challenger

- frontend/src/exams/exam-inventory-table.vue
Created custom sort so that table can sort first by icon severity and then by most recently added.
> Exam Inventory Table Sort by Icon

- frontend/src/exams/exam-inventory-table.vue
> Fix for session_number requirement in exam_inventory_table

- frontend/src/booking/scheduling-indicator.vue
- frontend/src/exams/add-exam-form-confirm.vue
- frontend/src/exams/edit-exam-form-modal.vue
- frontend/src/exams/exam-inventory-table.vue
- frontend/src/store/index.js
App was inconsistent with formatting/parsing of dates at capture, display and during POST/PUT actions.  All dates now captured in local time, submitted as UTC and converted to local time for display.  This eliminates the issue where DatePickers were showing the day before the actual date value held in the backend/store
> Fix Edit Exam Modal: Date Received / Expiry Date Inconsistency

- frontend/src/layout/nav.vue
Added condition to display of hamburger menu to prevent this from happening
> Fixed Issue w/ theQ where CSR able to navigate when serving citizen

- frontend/src/appointments/appointments.vue
- frontend/src/store/appointments-module.js
Notes were being captured but not displayed in the modal.  Fixed.
> Fixed Issue with Appointment Booking Modal Notes

- frontend/src/agenda/agenda.vue
- frontend/src/booking/other-booking-modal.vue
- frontend/src/layout/nav.vue
Previously this component was more complex and it relied on an invisible full-calendar instance to consume and parse the event data however this approach was causing issues.  Since the Agenda has recently been simplified and no longer supports multiple views etc., there is no need for full-calendar.  Have re-implemented using only moment.js and eliminated the errors related to full-calendar
> Fixed Errors in Branch Agenda

- api/app/admin/room.py
Client required rooms to be searchable through admin panels.
> Admin Panel - Room Searching

- api/app/admin/room.py
- api/app/resources/bookings/exam/exam_export_list.py
- frontend/src/exams/generate-financial-report-modal.vue
Client reported that financial reporting flag wasn't working properly. This has been fixed and tested to ensure that it's working as intended.
Client asked that there be an option added for ALL BOOKING EVENTS to the generate modal, and that there be an ALL EXAMS option as well. Not merging both options. This has been remedied and the UI to the modal has been updated to have a dropdown with filter options in the dropdown.
Client reported that the ITA and Non-ITA filters were reporting appointments and not just exams. This has been fixed and tested.
*During testing, an issue was found with creating rooms in the admin panel. This was fixed being utilizing the `is_created` param in the on_model_change function to check whether or not changes are happening during an EDIT or a CREATE.*
> Generate Financial Reporting - Bug Fixes

- frontend/src/assets/css/q.css
- frontend/src/serve-citizen/dash-hold-table.vue
- frontend/src/serve-citizen/dash-table.vue
- frontend/src/serve-citizen/serve-citizen.vue
- frontend/src/store/appointments-module.js
Appointments module now saves some appointment details to the citizen_comments key.  Modified the DashTable and DashHoldTable to display this data if present.  Modified the ServeCitizen modal to parse out the data on retrieval so it does not show in the comments box and parse it back in on submission so it is retained.
> Modified TheQ to show appointment details

- frontend/src/agenda/agenda.vue
- frontend/src/agenda/buttons-agenda.vue
- frontend/src/layout/nav.vue
Fixed: 
https://trello.com/c/9OXYVYFv (Calendar title bar text issue)
https://trello.com/c/0HMjvNR8 (Hamburger menu display issue)
> Calendar agenda view bug
