sjrumsby/queue-management

api/app/resources/theq/csrs.py

An active exam is deemed by it's booking id field being null as well as its expiry date field being greater than todays date. The response to the /csrs/me/ GET method now includes an array called 'active_exams' which lists all exams who meet the filtering requirements just outlined, as well as being exams being in the same office as the CSR that logs into theq.

Add Active Notifications to API

---

api/app/schemas/bookings/room_schema.py

Excluded the "booking" object from the room schema such that an array of booking ids was not returned when the GET rooms method was called.

Rooms Schema Bug Fix

---

api/postman/bookings-env-postman.json
api/postman/bookings-postman.json

Created new postman tests for development on the bookings feature for the queue. Exported files can be re-imported into Postman native application or be run via command line

Add and Embed Integration Tests

---

api/app/models/bookings/exam.py
api/app/resources/bookings/exam/exam_list.py
api/app/schemas/bookings/exam_schema.py
frontend/src/add-citizen/form-components/channel.vue
frontend/src/exams/exam-inventory-table.vue
frontend/src/store/index.js

Filtering adds very basic support for kwarg parameter passing from the front end. Can perform search filtering on a limited set of columns, and does not support deep search across relationships or complex search types (e.g., LIKE, OR, GTE, Dates, etc).
Does conditionally render the office for LIASON / GA roles in the table.

Added components for performing search filtering

---

api/app/models/bookings/exam.py

During testing, it was found out that the exam_returned_ind field on the exam table was set to nullable=false. When a new exam was created, this field was not attached to the POST method, which ended up in a 422 error code. This was fixed by adding a default value of zero to the column so that the nullable property of the field was not violated, which means on creation, exams are not returned.

Exam Returned Ind Default Value

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.vue
frontend/src/admin.vue
frontend/src/assets/css/q.css
frontend/src/booking/booking-modal.vue
frontend/src/booking/calendar.vue
frontend/src/booking/dropdown-calendar.vue
frontend/src/booking/edit-booking-modal.vue
frontend/src/booking/scheduling-indicator.vue
frontend/src/exams/exam-inventory-table.vue
frontend/src/layout/footer.vue
frontend/src/layout/header.vue
frontend/src/layout/nav.vue
frontend/src/router.js
frontend/src/serve-citizen/serve-citizen.vue
frontend/src/store/helpers.js
frontend/src/store/index.js

Created a component edit-booking-modal to handle both exam and other type events.  Supports all editable fields for a booking.  Dynamically updates the calendar in background and then posts changes on submit or reverts on cancel.  Also revamped layout to eliminate the need for the windowResize listener to calculate the viewport size.  All layout-related divs now styled with "position: relative" or "position: fixed" so browser can manage this task automatically.  This was necessary for changes introduced to SchedulingIndicator - component now appears at bottom of screen with footer.

Created edit-booking component and related changes

---

api/manage.py

During the last demo, it was found out that the bootstrap data for exam types had a typo in it. For consistency purposes during live demos, this data was amended to follow an XML file containing actual exam type values provided to Olivewood from John McColl.

Fix Bootstrap Data for Consistency

---

frontend/src/booking/calendar.vue
frontend/src/exams/exam-inventory-table.vue
frontend/src/router.js

Room Bookings users require easy access to editing information with respect to a single exam. With this being said, once an exam is booked, the booking itself might need to be changed. The exam inventory table presents an easy way for users to filter through all exams, and the actions field presents a way for the user to link directly to a particular exams booking quickly. Based on logic if a booking for an exam is present, a dropdown in the actions tab will show up called "Update Booking", and once clicked, the user is taken directly to the DAY view of the booking calendar where this exam is currently booked.
Future enhancements to this may include the user being brought directly to the edit booking modal to avoid confusion.

Link Single Exam to Booking Feature

---

api/app/resources/theq/csrs.py
api/manage.py
frontend/src/App.vue
frontend/src/login-warning.vue

When logging in, if the username does not exist in the Q System database, the call to /csrs/me will 500, leading to a poor front end experience. To clean this up, changes were made such that if the username did not exist /csrs/me returned a 404 response. The frontend had an bootstrap alert added such that if the username name did not exist BUT the user was logged in, the user would be warned saying to contact an administrator. The final step was to provisioni csr usernames in the Database for Sean, Scott, Adam, Chris and Karim for future use.

Fix Issues With Logins

---

frontend/src/store/index.js

During end of sprint code clean-up, it was found out that the examsOnLogin action in the index.js file was actually not used, and therefore redundant. This was cleaned up, and the bookings features tested on the front end to ensure that no negative side effects were created post action removal.

Code Clean-up: Redundant Vue Action

---

frontend/src/assets/css/q.css
frontend/src/exams/return-exam-form-modal.vue

During testing across multiple browsers of the edit and return exam modals, with their success/failure messages, it was found that there were some styling issues with respect to modal size. Issues being modal/messages modal size and whether or not there were scroll bars present depending on the size of screen. These issues were addresses in this PR.

Edit/Return Exam Modal Styling

---

api/postman/bookings-postman.json
documentation/open-api/swagger.yaml

During the development of the bookings app in sprint 4, a field was added to the exams model/schema, and a GET method was added to list all offices in theq. These changes needed to be reflected in the bookings postman tests, as well as in the swagger yaml file. The postman tests were written and tested before submission of this PR, and were verified to be working as expected.

Sprint 4 - Swagger/Postman Updates

---

api/app/resources/bookings/exam/exam_post.py
api/manage.py

During development of the bookings feature, it was found out that liasons could not POST exams from one office to a different office (ie// office_id 1 -> office_id 3). Since Liaisons require the ability to create exams in all offices, a change needed to be made to the exam POST end-point, checking for the csr role code to be LIAISON. Test data was also added to the manage.py file such that the role code LIASON exists now. A normal POST of an individual ITA exam was done in order to the test that previous functionality was not changed.

Issue with Liaison Role Creating Exams

---

frontend/src/exams/add-exam-form-components.js
frontend/src/exams/add-exam-form-modal.vue
frontend/src/exams/buttons-exams.vue
frontend/src/exams/exam-inventory-table.vue
frontend/src/exams/inventory-filters.vue
frontend/src/main.js
frontend/src/store/index.js

Improved the add exam workflow including addition of flatpickr.js for time selection, an 'add another exam' button at the end, and sepperated the access to the form to another button visible only to the LIAISON role.  Added filters to the exam inventory table for Group vs. Individual, Expired vs Current, and Booked vs Unbooked, as well as modified the location column to handle the longer location data associated with group exam bookings.  also fixed an issue causing the agenda and bookings views to render incorrectly when there are no bookings to display

Fixed various issues with add-group-exam workflow+filtering on exam table

---

api/app/resources/bookings/exam/exam_export_list.py
api/postman/bookings-postman.json
api/qsystem.py

As a finanace member, a bookings user will require to access an ability to gerenate a report or csv file to help generate a report on monthly/yearly revenues incurred from exams. In order to do this, a new end-point was added to GET all exams based on two url parameteres (start_date and end_date). Based on these parameters, the GET looks at all exams that were booked between those dates (exam and booking model are joined, then queried). Along with this new end-point, this PR includes a new set of postman tests to ensure that this end-point returns exactly what is required in order to generate these reports.

Monthly Financial Reports - Backend Changes

---

api/app/resources/bookings/booking/booking_post.py
api/qsystem.py
frontend/src/exams/generate-financial-report-modal.vue
frontend/src/exams/office-dropdown-filter.vue
frontend/src/store/index.js

A CSR/GA/Liaison will require the ability to generate financial reports based on type of exam as well as for a specific office. This PR contains the added functionality to add an exam_type and office_name url parameter to the url used to export a csv to the clients browser. At this moment in time, both parameters are not required or used when creatiung the CSV, but will be required in future development when generating these csv files.

Monthly Financial Reporting - Office/Exam Group Filtering

---

frontend/src/booking/calendar.vue
frontend/src/exams/exam-inventory-table.vue

After client testing, it was determined that the exam inventory table on the exam admin feature required the ability for exams that were not already booked, to be booked. Logic in the PR looks at an exam, and if it has not been booked, a dropdown item in the actions field will appear to Book this exam. Once clicked, the user is taken to the booking calendar feature (week view) and placed into scheduling mode with the exam that was clicked to be added. There the user can click on the calendar to place the exam into whatever time slot, in whatever room they want.

Booking Exam From Exam Admin Inventory Table

---

frontend/src/exams/add-exam-form-components.js
frontend/src/exams/add-exam-form-confirm.vue
frontend/src/exams/add-exam-form-controller.vue
frontend/src/exams/add-exam-form-modal.vue

Fixed issue whereby the confirmation page rendered dates inncorectly and was displaying irelevant headers/missing crucial information.  Also fixed a bug where the question "Was the exam received today" would only default to yes the first time the modal was launched without a page refresh.

Fixed issue with add exam form confirmation

---

frontend/src/exams/exam-inventory-table.vue
frontend/src/store/index.js

Clicking 'Edit Row' from the exam inventory table had no effect due to some property renaiming in the store that wasn't fully reflected throughout the rest of the front end code.  Also renamed 'Edit Row' to 'Edit Exam' for clarity.

Fixed issue where click 'Edit Row' did nothing

---

api/app/models/bookings/__init__.py
api/app/models/bookings/appointments.py
api/app/schemas/bookings/__init__.py
api/app/schemas/bookings/appointment_schema.py

CSRs were determined to need the ability to schedule smaller appointments on the bookings calendar feature for reasons other than exams. For this, an appointments model and schema were developed such that a separate calendar feature can be developed, separate from the exam bookings calendar. Future development will include GET, POST, PUT and DELETE http methods, as well as updates to postman tests and swagger api spec.

Scheduling Appointments - Models and Schemas

---

frontend/src/booking/calendar.vue
frontend/src/exams/exam-inventory-table.vue

During demo testing, it was found that the bookings calendar was selectable by default, allowing users to drag events onto the calendar without having an event in queue to be placed on the calendar. This was not required functionality on the calendar, and was deemed a bug. This bug was fixed by how the calendar.vue file looks for URL parameters, and how it sets the selectable option to true or false.

Remove Ability to Drag For Events on Bookings Calendar

---

frontend/src/agenda/agenda.vue
frontend/src/booking/calendar.vue
frontend/src/booking/edit-booking-modal.vue
frontend/src/exams/add-exam-form-components.js
frontend/src/exams/add-exam-form-modal.vue
frontend/src/exams/buttons-exams.vue
frontend/src/exams/edit-exam-form-modal.vue
frontend/src/exams/edit-group-exam-modal.vue
frontend/src/exams/exam-inventory-table.vue
frontend/src/exams/exams.vue
frontend/src/store/index.js

Created a new edit exam form that has multiple setups with different fields for the various types of CSRs that allows editing of all the required fields.  Built a new office search functionality that allows for typing directly into the input field with suggestions populating beneath or inputing the office number.
Also fixed previously undocumented bug which caused a exam_received_date to be set to the current date during the initial capture of a group exam--value now remains unset for branch staff to update when appropriate.

Created new edit exams modal and form

---

frontend/src/exams/generate-financial-report-modal.vue

After testing, it was determined that the generate CSV modal's datepicker was not using the same datepicker that the rest of Bookings was using. This was changed by importing the DatePicker component from the vu2-datepicker library and replacing the old date picker with the new one.

Generate CSV Date Picker

---

frontend/src/exams/edit-group-exam-modal.vue
frontend/src/exams/exam-inventory-table.vue
frontend/src/store/index.js

Fixed issue which was causing exam inventory filters not to work correctly following the addition of the sbc_staff_invigilated flag to the data model.  also fixed an issue with the tabular data display in the edit-group-exam-booking-modal and a bug with the inivigilator dropdown in same.  also added the ability to PUT an 'unassigned' invigilator to a group exam.

Fixed issue with exam inventory modal filters

---

frontend/src/exams/exam-inventory-table.vue

Previously, the scheduled column would show the unscheduled icon (yellow warning sign) for exams that were actually scheduled.  This was due to the recent addition of the 'sbc_staff_invigilated' field to the data model.  Added logic to check this field as well as invigilator_id in determining whether or not an exam has been scheduled.

Fixed issue with exam inventory "Scheduled" column

---

api/app/resources/bookings/exam/exam_export_list.py
frontend/src/exams/generate-financial-report-modal.vue

During testing of the generate csv modal, it was found that additional filters would be required. John McColl specifically asked for an "All Exams" option and "All Non-ITA Exams" option to be added to the filter options. These filters were added and then tested by adding multiple different exams were added in the span of a month, and then making sure that the csv generated for reported had the exact number of exams reported back that existed in the bookings calendar for that month.

Generate CSV Additional Filter Options

---

frontend/package-lock.json
frontend/package.json
frontend/src/exams/add-exam-form-components.js
frontend/src/exams/add-exam-form-confirm.vue
frontend/src/exams/add-exam-form-controller.vue
frontend/src/exams/add-exam-modal.vue
frontend/src/exams/buttons-exams.vue
frontend/src/exams/edit-exam-form-modal.vue
frontend/src/exams/office-drop.vue
frontend/src/main.js
frontend/src/store/index.js

Created an additional questions object in store for capture 'other' exam workflow, and edited the existing questions objects to require only 5 digit event_id numbers.  Refactored validation logic to allow for setting optional fields (minLength: 0, digits: false), and swapped in new office selection component.

Changed validation on exam form modal to require 5 digit event_id

---

frontend/src/booking/buttons-calendar.vue

Since the ITA Exam Event option is for all exam types, renamed the button in the dropdown menu to 'Exam Event'.

Changed wording in 'Schedule an Event' dropdown menu on Room Booking component

---

frontend/src/exams/return-exam-form-modal.vue
frontend/src/store/index.js

During testing it was found that the return exam functionality in the exam inventory table was broken. The process to break this function was to create an exam, book the exam and then return the exam immediately after booking. This was fixed by removing the selectedExam state from the return exam form modal and access the fields object instead.

Return Exam Functionality

---

frontend/src/exams/edit-exam-form-modal.vue

Fixed bug where the CSR view of the edit exam modal had outdated css selectors on its data table for displaying exam info.

Fixed Exam Info tabular data display in edit exam modal

---

api/app/schemas/bookings/booking_schema.py

Added the 'allow_none=True' flag to invigilator_id in the bookings schema to allow the field to be set to null now that the sbc_staff_invigilated flag has been implemented (therefor creating the practical need for updating the invigilator to null from a previously set value)

Modified booking schema to allow invigilator_id to be null

---

frontend/package-lock.json
frontend/src/booking/edit-booking-modal.vue
frontend/src/exams/add-exam-modal.vue
frontend/src/exams/delete-exam-modal.vue
frontend/src/exams/exam-inventory-table.vue
frontend/src/store/index.js

During testing, it was found out that the bookings feature lacked a function to delete an exam, not just the exam's booking. The exam-inventory table was modified to have a 'delete exam' dropdown action, which opens a confirmation modal. This modal displays basic exam information to the user before the user deletes the exam. This function has been tested using the CSR, GA and LIAISON roles.

Delete Exam Functionality

---

frontend/src/exams/exam-inventory-table.vue
frontend/src/store/index.js

During testing of the exam inventory table, it was found that the table required filters for exams that have been returned and exams that haven't been returned.Using infrastructure previously developed for filters that already exist, exams were filtered based on whether or not exam_returned_ind was 1 or 0 for the exams present in the table.

Add Exam Inventory Filter - Returned Exams

---

frontend/src/exams/add-exam-form-components.js
frontend/src/exams/buttons-exams.vue

After client testing, it was deemed necessary that the pesticide modal and button be removed and that old pesticide non-ita exams functionality be re-implemented. The button and modal and essentially been de-activated because they will be re-used at a later date for BC Mail Plus purposes.

Pesticide Button/Modal Removal

---

frontend/src/exams/add-exam-form-controller.vue
frontend/src/store/index.js

During client testing, it was found out that all fields that require actual char input (exam name, student name etc.) only required a minimum field length of 2 chars. This was addressed in this PR.

Add Exam Field Length

---

frontend/src/exams/delete-exam-modal.vue
frontend/src/exams/edit-exam-form-modal.vue
frontend/src/exams/exam-inventory-table.vue

During client testing, it was noted that delete functionality had to be moved from the exam inventory actions dropdown list to the edit exam details modal. This functionality was also required to delete any bookings that the selected deleted exam was associated to. This functionality was tested on booked and un-booked exams that included ITA, Non-ITA and Group exams.

New Delete Exams and Related Booking

---

frontend/src/exams/exam-inventory-table.vue

During testing, clients recommended that the color scheme for the filter buttons on the exam inventory table be changed to the BC Government color scheme. This was achieved by applying the primary variant class to the buttons, and modifying the active button color through css class manipulation to ensure that the selected blue provided enough contrast for users. Before submitting this PR, changes were approved by clients via Trello card for this issue.

Update Exam Inventory Filter Color Scheme

---

api/app/admin/__init__.py
api/app/admin/invigilator.py
api/app/admin/room.py
api/qsystem.py
frontend/src/buttons-admin.vue

Client requirements asked for new flask-admin panels for invigilators and rooms. Through these panels, users should be able to see a list of all rooms or all invigilators specific to the users office (not ALL rooms or ALL invigilators). This list of office specific rooms or office specific invigilators should have the ability to update and delete room records or invigilator records, and the admin panel should give the user the ability to create new rooms and invigilators as well.

Create/Update/Delete Invigilators/Rooms Per Office

---

frontend/src/assets/css/q.css
frontend/src/booking/edit-booking-modal.vue
frontend/src/exams/add-exam-form-components.js
frontend/src/exams/add-exam-form-controller.vue
frontend/src/exams/edit-group-exam-modal.vue
frontend/src/store/index.js

Fixed the edit-group-booking-modal re: issue not allowing submission of invigilator change.  Fixed the hang on the add pesticide exam form where the next button would not switch to enabled on the last step.  fixed issue causing the invigilator dropdown select list (in various places) to be blank when the invigilator is unassigned instead of saying 'unassigned'. several other very minor changes to better support IE11 users.

Various fixes for IE11 Comptability

---

api/manage.py
frontend/src/booking/calendar.vue
frontend/src/store/index.js

Clients indicated that they would like the default colors for onsite and offsite rooms to be changed. Manage.py now includes the default hex value for lighter daisy, as well as modifiying the calendar component and store to make sure offsite rooms now show up as lighter coral.

Calendar Room Colors

---

api/app/admin/invigilator.py
api/app/admin/room.py
frontend/src/buttons-admin.vue

Client testing found that GA access wasn't fully enabled for both
invigilaor and room panels. Also, clients asked for the return results
for both panels to be different based upon client role code. If the user
role code is GA, the return results for both room and invigilator will
be specific to that users office. If the users role code is SUPPORT,
then that user will see ALL results for ALL offices.

Admin Invigilator/Room Feedback

---

frontend/src/booking/booking-modal.vue

During client testing it was found that the invigilator "assign later"
option in the booking modal needed to be removed for individual exams.
This option exists as long as the Group Exam Ind field is set to 0 for
any given exam.

Remove Invigilator Assign Later Option

---

frontend/src/exams/edit-exam-form-modal.vue

During testing, it was found that the exam type drop down items for non-ita exams were showing up as the ITA exam types. This was fixed by placing a conditional filter on the examType objects returned based on whether or not the ita_ind field is set to 0 or 1.

Edit Non-ITA Exam Details Exam Types

---

api/app/admin/__init__.py
api/app/admin/examtype.py
api/qsystem.py
frontend/src/buttons-admin.vue

Client testing found that examtype admin panels would be required if new exam types were to be added in the future. This page is only accessable by users with the SUPPORT role, and can create/delete exam types, as well as editing ones that currently exist.

Exam Type Admin Panels

---

frontend/src/exams/add-exam-form-components.js
frontend/src/exams/add-exam-modal.vue
frontend/src/exams/buttons-exams.vue
frontend/src/exams/office-drop.vue
frontend/src/store/index.js

Pesticide exams needed to be broken out of the "Add Non-ITA Exam" button such that a pesticide designate liaison could add these exams on their own. This button that is viewable on the exam inventory page can only be seen by csrs with the field pesticide_designate set to 1. This Add Exam functionality mirrors the functionality of the Non-ITA exam creation, but incorperates a select office chooser as well, and displays a notes field on the summary. This functionality has been tested with the GA role and LIAISON role, both with and without the pesticide_designate column set to 1 to ensure that this functionality is completely on its own.

Pesticide Exams - Provide Functionality for Designate

---

api/migrations/sql_scripts/offices.sql

During testing of new back-end features, it was found out that the pre-population scripts for offices was incomplete. This PR addresses adding the 'appointments_enabled' field and initializing each office in the table with a value of 0.

SQL Script Clean-up

---

api/manage.py
frontend/src/Socket.vue
frontend/src/add-citizen/add-citizen-form.vue
frontend/src/add-citizen/add-citizen.vue
frontend/src/add-citizen/form-components/buttons.vue
frontend/src/add-citizen/form-components/filters.vue
frontend/src/add-citizen/form-components/tables.vue
frontend/src/assets/css/q.css
frontend/src/exams/exams.vue
frontend/src/layout/nav.vue
frontend/src/main.js
frontend/src/serve-citizen/dash-buttons.vue
frontend/src/serve-citizen/dash.vue
frontend/src/serve-citizen/serve-citizen.vue
frontend/src/store/index.js

Applied router navigation guard to dash.vue so that when navigating away from theQ to either Exam Management or Room Booking, the AddCitizenModal appears (simplified version) pre-filtered to "Exams" catagory of service_reqs.  User can select a catagory and proceed, and can finish time tracking by either clicking the icon which appears or returning to the Q.

Implemented Time Tracking Feature

---

frontend/src/layout/nav.vue

Client testing found that 'Exam Admin' in the nav hamburger dropdown list should be re-named 'Exam Inventory' to match the page name. This PR contains that fix.

Exam Admin Re-name

---

frontend/src/exams/buttons-exams.vue

Client testing found that if a user had the ita-designate flag set to 1 and was also a GA, that there were 2 'Add ITA Exam' buttons on the exam inventory page. There was also a random '1' added to the pesticide exam button, this was removed.

Exam Inventory - Buttons

---

frontend/src/exams/edit-exam-form-modal.vue
frontend/src/store/index.js

Client testing found issues with deleting exams through the edit exam modal. This issue can be attributed to a previous refactor, and has been resolved.

Exam Inventory - Delete Exam Not Working

---

frontend/src/exams/add-exam-form-components.js
frontend/src/exams/add-exam-modal.vue

Client testing found that the Pesticide Exam modal needed the exam type value to be preset to "Pesticide". This PR contains the fix for this issue by pre-setting the exam_type_id once the modal is opened, and validating the exam_type_id as well, such that the user can continue through the steps for creating an exam.

Pesticide Exam Modal - Preset/Validate Exam for Pesticide Exam Type

---

api/app/admin/csr.py

Client testing found that ITA, Pesticide, and Liaison designates needed to be re-named to properly reflect the csr's job title. This has been addressed in this PR.
- ITA -> Office Exam Manager
- Pesticide -> Pesticide Client Liaison/Program Specialist
- Liaison -> ITA Liaison/Program Specialist

Admin Panel - Designate Label Re-name

---

frontend/src/exams/exam-inventory-table.vue

Client testing found that if a user with vision impairment zooms in on the exam inventory table, that it didn't have a horizontal scroll automatically enabled. This was fixed by adding the 'responsive' prop to the b-table on the exam-inventory table component, and tested by zooming on the component to see whether or not a scroll bar became active if the component was larger than the actual screensize of the user.

Responsive Exam Inventory Table

---

frontend/src/booking/calendar.vue

Client testing found that bookings could be done in the past, which should not be allowed. This PR corrects this by adding logic to the config object of the calendar, checking to see if the start date of the event being created is before a datetime object called "Today" which goes down the minute value of the datetime object created. Example: If the time of the object created is 3:03pm of that day, the calendar will not allow you to create an event until the 3:30pm-4:00pm block.

Booking Calendar - Booking Events in the Past

---

frontend/src/exams/add-exam-form-components.js

Client testing found the "Ok" confirm at the bottom of the Exam Time select drop down was not necessary. This PR seeing the confirm option on the Time Question component removed to remedy this.

Group Exam Time Select

---

frontend/src/booking/edit-booking-modal.vue

Client testing found that vue input fields should have autocomplete disabled.
This was completed in a previous sprint, but developer testing found one field on the edit booking modal that didn't have this setting enabled.

Input Field - Disable Autocomplete

---

frontend/src/booking/edit-booking-modal.vue

Client testing found that the Collect Fees dropdown on the edit booking modal only had the "No" value enabled, and required a "Yes" value as well. This field had to map correctly to the fees field on the booking model. This PR adds this dropdown option and also ensures that the Put method to edit a particular booking works for this field now that it has been enabled.
Client also asked that the the 3 fields (fee amount, invoice to, name of entity to bill) that were enabled when the fees option was set to yes, were also to be removed, to be possibly implemented at a later date.

Need Collect Fees Yes/No

---

api/app/resources/bookings/exam/exam_list.py

Client testing found that the Exam Inventory table needed to filter out exams that were older than 90 days. This was implemented by altering the exams_list end-point to union two queries: one that fould find all exams where the exam_returned_date was null, and another where the exam_returned_date was greater than 90 days, then unioning the two subqueries together.

Filter out Exam Returned - 90 Days or Older

---

api/postman/bookings-env-postman.json

Client pointed out that refreshed enviornment variables weren't sent on the lastest PR. These were changed over a month ago with the move to localhost keycloak, but forgotten.

Postman Environment Variables

---

frontend/src/exams/delete-exam-modal.vue

After deleting an exam, the edit exam modal continues to display in the background. This change ensures that it closes correctly.

Ensure that edit exam modal closes when we delete an exam

---

frontend/package-lock.json
frontend/src/exams/buttons-exams.vue

During the handoff meeting, clients determined that this button should now be viewable by users with the ita_designate and financial_designate fields set to 1 and if a user is also a GA. This button was also modified to no longer be justified right on the button row, and is now in line with the rest of the buttons that show up on the exam inventory page.

Sprint 10 3 generate csv access

---

api/app/admin/examtype.py

Client testing found that columns labels with "_ind" were confusing (ind->individual, not ind->indicator), so this was changed to label the list table and table column fields to show 'Flag' instead of 'Ind'.

Exam Type Admin Panel - Ind Re-name

---

frontend/src/exams/buttons-exams.vue

During final client testing, it was found that the challenger/monthly sessional drop down needed to be visible to users with the office manager flag set to 1. This was resolved by adding the 'is_ita_designate' getting to the logic that controls whether or not this dropdown component is visible.

Chanllenger Exams - Show if User is Office Manager

---

frontend/src/booking/calendar.vue

Clients asked for the calendar events to show up with ~90% width of the calendar room column to allow users to place more than one event in the same time slot. I've confirmed that the 85% width the event is currently set to is satisfactory with the client already.

Calendar Event Width

---

frontend/src/exams/add-exam-form-components.js
frontend/src/exams/add-exam-modal.vue

Client has asked that the default exam type change that was made in commit
12d4014 be reverted since there are now going to be 3 different pesticide exam types (accounting for duration). A sort of the exam types has also been applied such that the list will now mirror functionality of all other exam type selections in all other add exam modal types.

Pesticide Exam - Revert Exam Type Changes

---

api/manage.py
frontend/src/store/index.js

Due to changes of the name of the above type of exam which were not updated throughout the frontend code, the examObject for that type of exam could not be located by searching by name and thus the exam details could not be populated for posting.  Have updated.

Fixed issue preventing Capture of Monthly Session Exams

---

frontend/src/exams/buttons-exams.vue

Client testing found that if a user had the Office Manager permission set to 1 and wasn't a GA, that two Add ITA Exam buttons would show on the exam invetory page. This issue was fixed by fixing partial logic on the buttons-exams such that a negation is now complete.

Two Add ITA Exam Buttons

---

frontend/src/exam-alert.vue

Client testing found that the notification banner was being rendering over top of modals. This was fixing by reducing the the z-index of the notification banner from 1041 to 1040.

Notification Z-Index

---

frontend/src/booking/booking-modal.vue
frontend/src/exams/add-exam-modal.vue
frontend/src/exams/success-exam-alert.vue

Client noted that during slow network periods that clicking submit buttons on create exams or create bookings would create multiple instances of that object. This has been resolved by adding '.once' to the @click property of the submit buttons on the add exam modal and add booking modal.

Click Once Submit Buttons

---

frontend/src/App.vue
frontend/src/assets/css/q.css
frontend/src/booking/booking-modal.vue
frontend/src/booking/calendar.vue
frontend/src/booking/scheduling-indicator.vue
frontend/src/exams/add-exam-form-components.js
frontend/src/exams/add-exam-modal.vue
frontend/src/exams/buttons-exams.vue
frontend/src/exams/exam-inventory-table.vue
frontend/src/store/add-exam-module.js
frontend/src/store/index.js

As the AddExamModal received no props, eliminated the need to save its state into another store key before switching routes to use the Calendar.  Now that the AddExamModal persists and is not destroyed on route changes there is no need to save and re-load its state.  Removed numerous actions, mutations, state keys and methods accross AddExamModal, BookingModal, AddExamModule and AddModalFormComponents.  Booking on-site now works.

Fixed Issue that prevented booking of session exams in office

---

frontend/src/booking/calendar.vue

Client testing found that the booking calendar events, when stacked on top of each other, were bleeding into other columns. This was fixed by changing the width css property to max-width of 85%.

Calendar Event Bleeding

---

frontend/src/exams/add-exam-form-components.js
frontend/src/exams/edit-exam-form-modal.vue
frontend/src/exams/edit-group-exam-modal.vue

Changed guards to allow CSRs as well as GA/Designates to edit all fields for the "other" exam type and removed the special case fields being displayed in favour of just showing the date and time pickers but with conditions on disabled prop.

Modified EditGroupBookingModal to Support Booking Other Exams Offsite

---

api/app/resources/bookings/exam/exam_list.py

Client testing found that the exam inventory table needed to be sorted from newest to oldest. This was accomplished by placing an order_by on the object generated in the exam-list endpoint to DESC sort based on the exam_id column.

Exam Inventory Sorting

---

api/app/admin/invigilator.py
api/app/admin/room.py

Due to use in production, clients found that the can_delete flag needed to be added to the room and invigilator panels due to flask admin ignoring FK contraints when deleting objects. The rooms panel now no longer has the ability to delete whatsoever, and the invigilator panel now selectively shows the delete button based on the users role.

Admin Panels - Delete Flag Based on User Roles

---

frontend/src/exams/edit-exam-form-modal.vue

Component local state storing values in object as keys which were initialized if they had preset values but exam_received_date is not set in this case and so the v-model was creating the key non-reactively.  Added exam_received_date: null to the predifined component local data to ensure reactivity.

Fix IE Issue: EditExamModal datepicker does not update on change

---

frontend/src/exams/return-exam-form-modal.vue

For unknown reasons, vue2-datepicker component needed date formatted differently to support IE.

Fixed Issue in IE11 where Return Exam Modal Did Not Populate Date

---

frontend/src/serve-citizen/serve-citizen.vue

At lower resolution/higher zoom/smaller screen sizes, modal layout did not previously alocate sufficient space to render all 3 form elements from the Serve Citizen Modal first row of modal action buttons/interactions (Quick Txn, Priority and Add Service button).  Changed layout of columns and added a flexbox to achieve alignment.

Fix Showstoper: Serve Citizen: Alignment of Buttons

---

frontend/src/add-citizen/add-citizen.vue

Stopped modal from retaining scroll position  unexpectedly.

Showstopper Fix: Add Citizen Modal: Scroll Memory

---

frontend/src/add-citizen/add-citizen.vue

Presently the backend rejects a request to submit a Appointment when the appointment does not include contact_information field.  This is contrary to what was discussed prior to building and has been corrected.

Fix Showstopper: Required Fields in Appointment Booking Modal

---

frontend/src/serve-citizen/serve-citizen.vue

Typo with new commit caused IE column rendering to push the quick transaction checkbox, priority select and add service button off of the add service modal.

Issue with IE Column Rendering

---

frontend/src/add-citizen/add-citizen.vue

Fixed scroll position memory by using v-if instead of using :key='math.random()' as this resulted in other unexpected issues.

Fix Showstopper:  Add Citizen Modal Usage of :key

---

frontend/src/exams/exam-inventory-table.vue

Challenger Exam Filter Criteria refer to session_number instead of event_id in error.  Re-worded and fixed.

Fix Exam Inventory Table Filters

---

api/app/schemas/bookings/appointment_schema.py
frontend/src/serve-citizen/serve-citizen.vue
frontend/src/store/index.js

Fix Appointment Booking Modal: Error 422 w/o Contact Info
Contact info did not have allow-none flag in schema.  Added it to comments as well.
+
Fix Showstopper:  Delay when loading Serve Citizen in the Q
Added a spinner to display while browser is parsing citizen data for display in modal to prevent invalid data messages from briefly appearing to user.

Fix various showstoppers

---

api/app/resources/bookings/exam/exam_export_list.py

Clients asked that if a user is a financial reporting designate to return ALL exams when the query for reporting is submited. Otherwise the exams returned to the user are filtered based upon the users office.

Financial Reporting - Filtering Offices

---

frontend/src/serve-citizen/serve-citizen.vue
frontend/src/store/index.js

Previously added trigger to show the spinner when clicking on a citizen from the queue table but failed to consider the scenarios of clicking on a citizen in the hold table or directly from the Add Citizen Modal.  Added triggers for the other ways to launch the modal.

Fix Serve Citizen Modal Loading Spinner

---

api/app/resources/theq/csrs.py

Clients noticed after production release that group exams were causing the notification banner to show if SBC Staff were selected as invigilators. This condition met the requirements of not having to notify staff about exams, and such was fixed by adding a filter the group exam object in the csrs/me endpoint that only counted exams with booking.sbc_staff_invigilated == 0. This was tested by creating a group exam object, then creating a booking for this exams without an inviglator and making sure the notification would present itself on refresh. Then, altering the booking to have SBC staff invigilate the booking, refreshing the page to make sure no notification was present. Finally, the booking was altered to have an actual invigilator present for the booking, and refreshing the page to …

Group Exam Notifications - SBC Staff

---

frontend/src/exams/edit-group-exam-modal.vue

Exam dates can no longer be edited to a date that is in the past.  Also fixed eratic form validation that prevented the submit button from being pressed when certain dates were selected.

Fixed Edit Group Exam Modal to Disable Past Date Selection

---

frontend/src/exams/edit-exam-form-modal.vue
frontend/src/exams/return-exam-form-modal.vue
frontend/src/exams/success-exam-alert.vue
frontend/src/store/index.js

Logic controlling access to the full version of the Edit Exam Modal did not consider the ita_designate key.  Office Manager previously saw only the fields-limited CSR version.   Changed so that office mgr has same access as GA role.  Also fixed:
-liaison_designate were unable to edit office of pesticide exams or delete exams they add in error
-the exam_type field of the EditExamModal was listing exam_types which did not make sense. Disabled the ability to switch exam_type on a pesticide exam or challenger exam at all and restricted changing 'other' 'individual ita' and 'group ita' to exam type options of their catagory only.
-adjusted the other field-display and field-disable logic to ensure access to necessary features for office managers
-set the time of the editExamSuccess banner to 3 …

Fix to Allow Office Mgr to Edit Group/Session Exam Details + others

---

frontend/src/appointments/appointments.vue
frontend/src/exams/add-exam-form-controller.vue
frontend/src/exams/edit-exam-form-modal.vue
frontend/src/exams/edit-group-exam-modal.vue
frontend/src/exams/exam-inventory-table.vue
frontend/src/exams/return-exam-form-modal.vue

-Action Taken field now displays an error at the maximum input length and prevents further input
-Adjusted the exam_inventory table to display the life-ring error symbol on any exam assigned to a deleted invigilator and adjusted the filters to show such exams as not ready.
-Changed a call to a method by previous name (which was revised so was null reference) in EditGroupBooking modal

Return Exam fix: Action Taken Length & Deleted Invigilator Changes

---

api/app/admin/room.py

Clients required there to be a warning given to admin users if a room is about to have a deleted date applied to it, but it currently being used for bookings in the future. The flask admin on_model_change method was used to detect changes in the deleted date field before submission, and looking at the booking model for instances of such a room being used with start times greater than today (doesn't care about historical instances). If the room isn't in use, the room can be deleted. If the room is in use, and error message propagates telling the user that they were unable to apply the deleted date. Any other changes that the user might make on top of applying a deleted date to a room in use will be saved.

Delete Room Admin Warning

---

frontend/src/add-citizen/form-components/filters.vue
frontend/src/add-citizen/form-components/tables.vue
frontend/src/layout/nav.vue
frontend/src/serve-citizen/dash-buttons.vue
frontend/src/serve-citizen/dash-hold-table.vue
frontend/src/serve-citizen/dash-table.vue
frontend/src/serve-citizen/dash.vue
frontend/src/serve-citizen/serve-citizen-table.vue
frontend/src/serve-citizen/serve-citizen.vue
frontend/src/store/index.js

Changed the Minimize Button of the Serve Citizen Modal to hide the modal (on the condition that the Service Begun button has been pressed.  If citizen is 'invited' only, will revert to previous collapse behaviour).
Added conditions to Dash Table, Hold Table, router Navigation Guard for automatic ticket creation in exams, and Dash Buttons, to prevent starting additional tickets with current ticket minimized.
Adjusted Simplified Add Service Modal to display the catagories option but default it to 'Exams' instead of hiding it and fixing it on Exams only.  Adjusted the Serve Citizen modal to allow creation of ticket from Outside the Q and display message indicating noa active ticket when there is none.

Service Ctzn Mnmize Button now hides Modal + Allows Navigation

---

frontend/src/Login.vue
frontend/src/router.js

Clients required that the count of citizens waiting in queue be present on the page for users based on the following:
- if the office was a reception office (smart board type: nocallonsmartboard)
- if the route of the app is either 'exams' or 'bookings'
Based on this, logic from the Q route was re-used to display the citizen waiting count now in the application header.

Phase 1 - Active Citizen Count

---

frontend/src/appointments/appointments.vue

This PR addresses client feedback where only one appointment was allowed to be scheduled per given timeslot available in an office. The appointments calendar effectively works like the bookings calendar now, with the calendar background behind a scheduled event being made clickable now. Initial width of a given event in the column is 85% of it's max-width, but after a second event is scheduled, the remaining clickable column width returns to 5%.

Phase 1 - Multiple Appointment Bookings

---

frontend/src/booking/other-booking-modal.vue

Clients noted that when booking multiple back-to-back non-exam events in the bookings calendar, that the contact information from the previous booking would carry forward.
This bug was resolved by setting the contact information variable for the other booking to modal to be an empty string after the POST has completed.

Phase 1 - Non Exam Booking Contact Information

---

frontend/src/exams/edit-exam-form-modal.vue

Clients noticed that ITA Liaison users were unable to edit candidate names for pesticide exams. The logic that controlled this field on the edit exam for did not include the pesticide exam type, and was edited to include this exam type.

Phase 1 - Pesticide Exam Candidate Name

---

frontend/src/exams/add-exam-modal.vue

Client noticed that when Group exams were created in series, the Office Name/Number fields were pre populated with the previous created exams value, instead of being blank. Also, validation of the field was already happening if the field was blank, which was definitely a bug. This bug was resolved by removing the office_id value being set on initialization of the add exam modal for group and pesticide exams.

Phase 1 - Group/Pesticide Exam Office Validation

---

frontend/src/booking/edit-booking-modal.vue

Clients required that when a booking is rescheduled, that the invigilator for that booking is removed. In order to do this, a rescheduling flag was added to the edit-booking-modal, such that if the rescheduling button is pressed, this flag is set to true. When the modal is shown, logic was added such that if the flag is true, the invigilator object is set to null which changes the invigilator drop down to null, and when the modal is submitted the invigilator id for that booking is set to null.

Phase 1 - Reset Invigilator When Booking is Rescheduled.
